import { getDefaultConfig } from '@rainbow-me/rainbowkit';
import {
  mainnet,
  polygon,
  arbitrum,
  base,
  optimism,
  avalanche,
  bsc,
  gnosis,
  fantom,
  zkSync,
  celo,
  aurora,
  harmonyOne,
  moonbeam,
  moonriver,
  cronos,
  scroll,
  mantle,
  linea,
  polygonZkEvm,
  zora,
  sepolia,
  goerli,
  arbitrumSepolia,
  baseSepolia,
  optimismSepolia,
  polygonMumbai,
} from 'wagmi/chains';

export const config = getDefaultConfig({
  appName: 'Safe Transfers',
  projectId: process.env.NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID || 'YOUR_PROJECT_ID',
  chains: [
    // Mainnets
    mainnet,
    polygon,
    arbitrum,
    base,
    optimism,
    avalanche,
    bsc,
    gnosis,
    fantom,
    zkSync,
    celo,
    aurora,
    harmonyOne,
    moonbeam,
    moonriver,
    cronos,
    scroll,
    mantle,
    linea,
    polygonZkEvm,
    zora,
    // Testnets (only in development)
    ...(process.env.NODE_ENV === 'development' ? [
      sepolia,
      goerli,
      arbitrumSepolia,
      baseSepolia,
      optimismSepolia,
      polygonMumbai,
    ] : []),
  ],
  ssr: true,
});
